<!DOCTYPE html>
<html lang="sr">
<head>
    <meta charset="utf-8"/>
    <title>ninagro - Proizvodnja kartonske ambalaže od valovite lepenke</title>
    <meta name="author" content="Miloš Andrić">
    <meta name="description" content="Kompanija NINAGRO o.d. iz Sremske Mitrovice, čija je osnovna delatnost proizvodnja kartonske ambalaže od talasastog kartona (valovite lepenke).">
    <!-- Mobile Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <!-- Web Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Lato:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,300,100,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=PT+Serif' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="bootstrap/css/bootstrap.css" rel="stylesheet">
    <!-- Font Awesome CSS -->
    <link href="fonts/font-awesome/css/font-awesome.css" rel="stylesheet">
    <!-- Fontello CSS -->
    <link href="fonts/fontello/css/fontello.css" rel="stylesheet">
    <!-- Photoswipe CSS file -->
    <link rel="stylesheet" href="bower_components/photoswipe/dist/photoswipe.css"> 
    <link rel="stylesheet" href="bower_components/photoswipe/dist/default-skin/default-skin.css"> 
    <!-- Plugins -->
    <link href="plugins/magnific-popup/magnific-popup.css" rel="stylesheet">
    <link href="css/animations.css" rel="stylesheet">
    <link href="plugins/fullpage/jquery.fullpage.min.css" rel="stylesheet">
    <link href="plugins/owl-carousel/owl.carousel.css" rel="stylesheet">
    <link href="plugins/owl-carousel/owl.transitions.css" rel="stylesheet">
    <link href="plugins/hover/hover-min.css" rel="stylesheet">      

    <!-- The Project's core CSS file -->
    <link href="css/style.css" rel="stylesheet" >
    <!-- The Project's Typography CSS file, includes used fonts -->
    <!-- Used font for body: Lato -->
    <!-- Used font for headings: Roboto Slab -->
    <link href="css/typography-scheme-2.css" rel="stylesheet" >
    <!-- Color Scheme (In order to change the color scheme, replace the blue.css with the color scheme that you prefer)-->
    <link href="css/skins/green.css" rel="stylesheet">


    <!-- Custom css --> 
    <link href="css/custom.css" rel="stylesheet">
</head>
<body class="no-trans front-page transparent-header gradient-background-header full-page">

    <!-- scrollToTop -->
    <!-- ================ -->
    <div class="scrollToTop circle"><i class="icon-up-open-big"></i></div>

    <!-- page wrapper start -->
    <!-- ================ -->
    <div class="page-wrapper">

        <!-- header-container start -->
        <div class="header-container">
            <!-- header start -->
            <!-- classes:  -->
            <!-- "fixed": enables fixed navigation mode (sticky menu) e.g. class="header fixed clearfix" -->
            <!-- "dark": dark version of header e.g. class="header dark clearfix" -->
            <!-- "full-width": mandatory class for the full-width menu layout -->
            <!-- "centered": mandatory class for the centered logo layout -->
            <!-- ================ --> 
            <header class="header fixed-before full-width">
                <!-- header-right start -->
                <!-- ================ -->
                <div class="header-right clearfix">
                    <!-- main-navigation start -->
                    <!-- classes: -->
                    <!-- "onclick": Makes the dropdowns open on click, this the default bootstrap behavior e.g. class="main-navigation onclick" -->
                    <!-- "animated": Enables animations on dropdowns opening e.g. class="main-navigation animated" -->
                    <!-- "with-dropdown-buttons": Mandatory class that adds extra space, to the main navigation, for the search and cart dropdowns -->
                    <!-- ================ -->
                    <div class="main-navigation animated" style="background:#303538">
                        <!-- navbar start -->
                        <!-- ================ -->
                        <nav class="navbar navbar-default" role="navigation">
                            <div class="container-fluid">

                                <div class="container-fluid">

                                    <!-- Toggle get grouped for better mobile display -->
                                    <div class="navbar-header">
                                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                                            <span class="sr-only">Toggle navigation</span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>
                                        
                                        <!-- header-left start -->
                                        <!-- ================ -->
                                        <div class="header-left clearfix">

                                            <!-- logo -->
                                            <div id="logo" class="logo">
                                               <!--  <a href="index.html"><img id="logo_img" src="images/box.png" alt="box_icon" width="45px"></a> -->
                                               <img src="/images/ninLogoBW.png" width="200px" style="margin: auto; margin-top: -20px">
                                            </div>
                                        </div>
                                        <!-- header-left end -->
                                        
                                    </div>
                                    <!-- Collect the nav links, forms, and other content for toggling -->
                                    <div class="collapse navbar-collapse" id="navbar-collapse-1">
                                        <ul id="fullpage-menu" class="nav navbar-nav navbar-right">
                                            <li data-menuanchor="dobrodošli" class="hoverLinks"><a href="#dobrodošli" style="text-shadow: none; border: none; color: white">Dobrodošli</a></li>
                                            <li data-menuanchor="o_nama" class="hoverLinks"><a href="#o_nama" style="text-shadow: none; color: white;border:none">O nama</a></li>
                                            <li data-menuanchor="proizvodi" class="hoverLinks"><a href="#proizvodi" style="text-shadow: none;color:white;border:none">Proizvodi</a></li>
                                            <li data-menuanchor="galerija" class="hoverLinks"><a href="#galerija" style="text-shadow: none; color:white; border:none">Galerija</a></li>
                                            <li data-menuanchor="kontakt" class="hoverLinks"><a href="#kontakt" style="text-shadow: none;color:white;border:none">Kontakt</a></li>
                                        </ul>
                                    </div>

                                </div>
                            </nav>
                            <!-- navbar end -->

                        </div>
                        <!-- main-navigation end -->
                    </div>
                    <!-- header-right end -->
                </header>
                <!-- header end -->
            </div>
            <!-- header-container end -->

            <div class="fullpage-site-with-menu">

                <!-- section start -->
                <!-- ================ -->
                <section id="section-1" class="section dark-translucent-bg" style="background: url('images/img03.jpg'); background-size: cover;
                background-repeat: no-repeat;background-position: 0% 60%;">
                
                <div class="container">
             
                    <div class="row" style="position: relative;bottom:-130px;text-align: center;">
                         <a href="#o_nama" class="button aboutUs" style=" background: rgba(255,255,255,0.1);border:1px solid white;border-radius: 2px;padding: 10px 20px; text-decoration: none;"><b>Više o nama</b></a>
                    </div>
                    <div class="row">

                    
                        <div class="col-md-10 col-md-offset-1" style="margin-top: 200px">
                       
                        <div class="container" style="width: 100%">
                            <!-- <img src="/images/ninLogo.png" width="400px" style="margin: auto"> -->
                        </div>

                            <div class="text-center">
                                <!-- <h1 class="title large object-non-visible" data-animation-effect="zoomIn" style="font-family: 'Alfa Slab One', cursive;font-size: 53px">ninagro</span></h1> -->
                                
                                <!-- <div class="separator"></div> -->
                                <!-- <p class="object-non-visible" data-animation-effect="zoomIn" data-effect-delay="300" style="font-size: 20px">Proizvodnja kartonske ambalaže od valovite lepenke</p> -->
                                

                                <div class="col-md-12" style="margin-top: 20px;">
                                    <div class="col-md-3" style="padding-left: 3px; padding-right: 3px">
                                        <div class="blackout">
                                            <div class="productElements">
                                                <div>
                                                    <img src="images/ameriken_kutija.jpg">
                                                </div>

                                                <div>
                                                    <h4 style="color:black">Ameriken kutije</h4>
                                                    <p>Osnovni tip kutija koje izrađujemo od troslojne i petoslojne valovite lepenke, različitih kvaliteta sa štampom i bez.</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3" style="padding-left: 3px; padding-right: 3px">
                                    <div  style="border:1px solid white; background: white; color:black;box-shadow: 0px 0px 40px #000">
                                        <div>
                                            <img src="images/samosloziva_kutija.jpg">
                                        </div>
                                        <div>
                                             <h4 style="color:black">Samoslozive kutije</h4>
                                            <p>Osnovni tip kutija koje izrađujemo od troslojne i petoslojne valovite lepenke, različitih kvaliteta sa štampom i bez.</p>
                                        </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3" style="padding-left: 3px; padding-right: 3px" >
                                    <div style="border:1px solid white; background: white; color:black; box-shadow: 0px 0px 40px #000;">
                                        <div>
                                            <img src="images/pizza_kutija.jpg">
                                        </div>
                                        <div>
                                            <h4 style="color:black">Kutije za picu i hranu</h4>
                                            <p>Osnovni tip kutija koje izrađujemo od troslojne i petoslojne valovite lepenke, različitih kvaliteta sa štampom i bez.</p>
                                        </div>
                                        </div>
                                    </div>

                                    <div class="col-md-3" style="padding-left: 3px; padding-right: 3px">
                                    <div style="border:1px solid white; background: white; color:black; box-shadow: 0px 0px 40px #000">
                                        <div>
                                            <img src="images/gajbica_kutija.jpg">
                                        </div>
                                        <div>
                                            <h4 style="color:black">Kartonske gajbice</h4>
                                            <p>Osnovni tip kutija koje izrađujemo od troslojne i petoslojne valovite lepenke, različitih kvaliteta sa štampom i bez.</p>
                                        </div>
                                        </div>
                                    </div>
                                    
                                </div>
                                <!-- <a href="#o_nama" class="btn btn-lg moving smooth-scroll"><i class="icon-down-open-big"></i><i class="icon-down-open-big"></i></a> -->
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- section end -->

            <!-- section start -->
            <!-- ================ -->
            <section id="section-2" class="section">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2 pv-20" style="font-family: 'Roboto', sans-serif;">
                            <h2 class="title text-center">O nama</h2>
                            <div class="separator with-icon"><i class="fa fa-info bordered"></i></div>
                            <h3>Od 1993</h3>
                            <p>Kompanija NINAGRO o.d. iz Sremske Mitrovice počela je sa radom 1993. godine, čija je osnovna delatnost proizvodnja kartonske ambalaže od talasastog kartona (valovite lepenke).</p>

                            <p>Permanentnim višedecenijskim ulaganjem u infrastrukturu i opremu, kao i osposobljavanjem kadrova, danas smo u mogućnosti da u toj delatnosti adekvatno odgovorimo većini zahteva tržišta u pogledu kvaliteta, količina i raznovrsnosti kao i u pogledu rokova i cena, što nas svrstava u značajnije proizvođače kartonske ambalaže.</p>
                        </div>
                    </div>
                </div>
            </section>
            <!-- section end -->
            <!-- section start -->
            <!-- ================ -->
            <section id="section-2" class="section">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2 pv-20" style="font-family: 'Roboto', sans-serif;">
                            <h2 class="title text-center">Proizvodni asortiman</h2>
                            <div class="separator with-icon"><i class="fa fa-info bordered"></i></div>
                            <div style="margin-top: 40px">
                                <p>Tipovi kutija koje se proizvode su Ameriken i samosložive kartonske kutije od troslojne i petoslojne valovite lepenke sa mogućnosti štampe u više boja koje mogu biti lepljene ili šivene. U ponudi su i kartonski ulošci, pregrade, tacne lepljene u 4 tačke, raznih dimenzija i oblika po zahtevu kupca.</p>

                                <p>Takođe, sopstvenim prevoznim sredstvima, vršimo prevoz naših proizvoda do odredišta kupca.</p>
                            </div>
                            <div style="margin-top: 40px;">
                                <h3>Sertifikati</h3>
                                <p>Kompanija NINAGRO o.d. poseduje validne sertifikate:</p>
                                <p><b>SRPS ISO 9001:2008</b></p>
                                <p><b>SRPS ISO 14001:2005</b></p>

                                <p>čime ispunjava zahteve za područja sertifikacije: Proizvodnja kartonske ambalaže od valovite lepenke.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- section end -->

            <!-- section start -->
            <!-- ================ -->
            <section id="section-3" class="section dark-translucent-bg">
             <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators" style="bottom: 30px">
                  <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                  <li data-target="#myCarousel" data-slide-to="1"></li>
                  <li data-target="#myCarousel" data-slide-to="2"></li>
                  <li data-target="#myCarousel" data-slide-to="3"></li>
                  <li data-target="#myCarousel" data-slide-to="4"></li>
                  <li data-target="#myCarousel" data-slide-to="5"></li>
              </ol>

              <!-- Wrapper for slides -->
              <div class="carousel-inner" role="listbox" style="height: 100vh">
                <div class="item active">
                    <img src="images/IMG_1108.jpg" alt="Chania">
                </div>
                <div class="item">
                    <img src="images/ninagro02.jpg" alt="Chania">
                </div>
                <div class="item">
                    <img src="images/ninagro03.jpg" alt="Chania">
                </div>
                <div class="item">
                    <img src="images/gluing_maschine.jpg" alt="Chania">
                </div>
                <div class="item">
                    <img src="images/frames.jpg" alt="Chania">
                </div>
                <div class="item">
                    <img src="images/curioni_new.jpg" alt="Chania">
                </div>

            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
          </a>
      </div>
  </section>


  <!-- ================ -->
  <section id="section-4" class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-8 text-center col-md-offset-2 pv-20" style="font-family: 'Roboto', sans-serif;">
                <h2 class="text-center">Kontakt</h2>
                <div class="separator with-icon"><i class="fa fa-phone bordered"></i></div>
                <p class="lead text-center">Ukoliko imate pitanja ili želite da saznate više informacija, kontaktirajte nas putem sledećih kontakt podataka. Očekujemo vaš poziv!</p>
                <ul class="list-inline mb-20 text-center">
                    <li><i class="text-default fa fa-map-marker pr-5"></i>Manđeloški put, bb<br> 22000 Sremska Mitrovica</li>
                    <li><a href="tel:+38122631530" class="link-dark"><i class="text-default fa fa-phone pl-10 pr-5"></i>+381 22/631-530</a><br>
                    <a href="tel:+38122631512" class="link-dark" style="margin-left: 27px">+381 22/631-512</a>
                    </li>

                    <li><a href="mailto:ninagro@mts.rs" class="link-dark"><i class="text-default fa fa-envelope-o pl-10 pr-5"></i>ninagro@mts.rs</a><br>
                    <a href="mailto:ninagrooffice@gmail.com" class="link-dark" style="margin-left: 10px">ninagrooffice@gmail.com</a>
                    </li>
                </ul>
                <div class="separator"></div>
            </div>
        </div>
    </div>
</section>
<!-- section end -->
</div>

<!-- .subfooter start -->
<!-- ================ -->
<div class="subfooter">
    <div class="container">
        <div class="subfooter-inner">
            <div class="row">
                <div class="col-md-12">
                    <p class="text-center">Copyright © <?php echo date("Y"); ?> Coded by <a target="_blank" href="http://milosandric.tk">Miloš Andrić</a>. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- footer end -->

</div>
<!-- Root element of PhotoSwipe. Must have class pswp. -->
<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

    <!-- Background of PhotoSwipe. 
    It's a separate element, as animating opacity is faster than rgba(). -->
    <div class="pswp__bg"></div>

    <!-- Slides wrapper with overflow:hidden. -->
    <div class="pswp__scroll-wrap">

        <!-- Container that holds slides. PhotoSwipe keeps only 3 slides in DOM to save memory. -->
        <!-- don't modify these 3 pswp__item elements, data is added later on. -->
        <div class="pswp__container">
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
        </div>

        <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
        <div class="pswp__ui pswp__ui--hidden">

            <div class="pswp__top-bar">

                <!--  Controls are self-explanatory. Order can be changed. -->

                <div class="pswp__counter"></div>

                <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>

                <button class="pswp__button pswp__button--share" title="Share"></button>

                <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>

                <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

                <!-- Preloader demo http://codepen.io/dimsemenov/pen/yyBWoR -->
                <!-- element will get class pswp__preloader--active when preloader is running -->
                <div class="pswp__preloader">
                    <div class="pswp__preloader__icn">
                      <div class="pswp__preloader__cut">
                        <div class="pswp__preloader__donut"></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
            <div class="pswp__share-tooltip"></div> 
        </div>

        <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
        </button>

        <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
        </button>

        <div class="pswp__caption">
            <div class="pswp__caption__center"></div>
        </div>

    </div>

</div>

</div>
<!-- page-wrapper end -->

<!-- JavaScript files placed at the end of the document so the pages load faster -->
<!-- ================================================== -->
<!-- Jquery and Bootstap core js files -->
<script type="text/javascript" src="plugins/jquery.min.js"></script>
<script type="text/javascript" src="bootstrap/js/bootstrap.min.js"></script>
<!-- Modernizr javascript -->
<script type="text/javascript" src="plugins/modernizr.js"></script>
<!-- Fullpage javascript -->
<script type="text/javascript" src="plugins/slimscroll/jquery.slimscroll.min.js"></script>
<script type="text/javascript" src="plugins/fullpage/jquery.fullpage.js"></script>
<!-- Isotope javascript -->
<script type="text/javascript" src="plugins/isotope/isotope.pkgd.min.js"></script>
<!-- Magnific Popup javascript -->
<script type="text/javascript" src="plugins/magnific-popup/jquery.magnific-popup.min.js"></script>
<!-- Appear javascript -->
<script type="text/javascript" src="plugins/waypoints/jquery.waypoints.min.js"></script>
<!-- Count To javascript -->
<script type="text/javascript" src="plugins/jquery.countTo.js"></script>
<!-- Parallax javascript -->
<script src="plugins/jquery.parallax-1.1.3.js"></script>
<!-- Contact form -->
<script src="plugins/jquery.validate.js"></script>
<!-- Background Video -->
<script src="plugins/vide/jquery.vide.js"></script>
<!-- Owl carousel javascript -->
<script type="text/javascript" src="plugins/owl-carousel/owl.carousel.js"></script>
<!-- SmoothScroll javascript -->
<script type="text/javascript" src="plugins/jquery.browser.js"></script>
<script type="text/javascript" src="plugins/SmoothScroll.js"></script>
<!-- Initialization of Plugins -->
<script type="text/javascript" src="js/template.js"></script>
<!-- Custom Scripts -->
<script type="text/javascript" src="js/custom.js"></script>
<!-- Core JS file -->
<script src="bower_components/photoswipe/dist/photoswipe.min.js"></script> 
<!-- UI JS file -->
<script src="bower_components/photoswipe/dist/photoswipe-ui-default.min.js"></script> 
<script type="text/javascript">
    var initPhotoSwipeFromDOM = function(gallerySelector) {

    // parse slide data (url, title, size ...) from DOM elements 
    // (children of gallerySelector)
    var parseThumbnailElements = function(el) {
        var thumbElements = el.childNodes,
        numNodes = thumbElements.length,
        items = [],
        figureEl,
        linkEl,
        size,
        item;

        for(var i = 0; i < numNodes; i++) {

            figureEl = thumbElements[i]; // <figure> element

            // include only element nodes 
            if(figureEl.nodeType !== 1) {
                continue;
            }

            linkEl = figureEl.children[0]; // <a> element

            size = linkEl.getAttribute('data-size').split('x');

            // create slide object
            item = {
                src: linkEl.getAttribute('href'),
                w: parseInt(size[0], 10),
                h: parseInt(size[1], 10)
            };



            if(figureEl.children.length > 1) {
                // <figcaption> content
                item.title = figureEl.children[1].innerHTML; 
            }

            if(linkEl.children.length > 0) {
                // <img> thumbnail element, retrieving thumbnail url
                item.msrc = linkEl.children[0].getAttribute('src');
            } 

            item.el = figureEl; // save link to element for getThumbBoundsFn
            items.push(item);
        }

        return items;
    };

    // find nearest parent element
    var closest = function closest(el, fn) {
        return el && ( fn(el) ? el : closest(el.parentNode, fn) );
    };

    // triggers when user clicks on thumbnail
    var onThumbnailsClick = function(e) {
        e = e || window.event;
        e.preventDefault ? e.preventDefault() : e.returnValue = false;

        var eTarget = e.target || e.srcElement;

        // find root element of slide
        var clickedListItem = closest(eTarget, function(el) {
            return (el.tagName && el.tagName.toUpperCase() === 'FIGURE');
        });

        if(!clickedListItem) {
            return;
        }

        // find index of clicked item by looping through all child nodes
        // alternatively, you may define index via data- attribute
        var clickedGallery = clickedListItem.parentNode,
        childNodes = clickedListItem.parentNode.childNodes,
        numChildNodes = childNodes.length,
        nodeIndex = 0,
        index;

        for (var i = 0; i < numChildNodes; i++) {
            if(childNodes[i].nodeType !== 1) { 
                continue; 
            }

            if(childNodes[i] === clickedListItem) {
                index = nodeIndex;
                break;
            }
            nodeIndex++;
        }



        if(index >= 0) {
            // open PhotoSwipe if valid index found
            openPhotoSwipe( index, clickedGallery );
        }
        return false;
    };

    // parse picture index and gallery index from URL (#&pid=1&gid=2)
    var photoswipeParseHash = function() {
        var hash = window.location.hash.substring(1),
        params = {};

        if(hash.length < 5) {
            return params;
        }

        var vars = hash.split('&');
        for (var i = 0; i < vars.length; i++) {
            if(!vars[i]) {
                continue;
            }
            var pair = vars[i].split('=');  
            if(pair.length < 2) {
                continue;
            }           
            params[pair[0]] = pair[1];
        }

        if(params.gid) {
            params.gid = parseInt(params.gid, 10);
        }

        return params;
    };

    var openPhotoSwipe = function(index, galleryElement, disableAnimation, fromURL) {
        var pswpElement = document.querySelectorAll('.pswp')[0],
        gallery,
        options,
        items;

        items = parseThumbnailElements(galleryElement);

        // define options (if needed)
        options = {

            // define gallery index (for URL)
            galleryUID: galleryElement.getAttribute('data-pswp-uid'),

            getThumbBoundsFn: function(index) {
                // See Options -> getThumbBoundsFn section of documentation for more info
                var thumbnail = items[index].el.getElementsByTagName('img')[0], // find thumbnail
                pageYScroll = window.pageYOffset || document.documentElement.scrollTop,
                rect = thumbnail.getBoundingClientRect(); 

                return {x:rect.left, y:rect.top + pageYScroll, w:rect.width};
            }

        };

        // PhotoSwipe opened from URL
        if(fromURL) {
            if(options.galleryPIDs) {
                // parse real index when custom PIDs are used 
                // http://photoswipe.com/documentation/faq.html#custom-pid-in-url
                for(var j = 0; j < items.length; j++) {
                    if(items[j].pid == index) {
                        options.index = j;
                        break;
                    }
                }
            } else {
                // in URL indexes start from 1
                options.index = parseInt(index, 10) - 1;
            }
        } else {
            options.index = parseInt(index, 10);
        }

        // exit if index not found
        if( isNaN(options.index) ) {
            return;
        }

        if(disableAnimation) {
            options.showAnimationDuration = 0;
        }

        // Pass data to PhotoSwipe and initialize it
        gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, items, options);
        gallery.init();
    };

    // loop through all gallery elements and bind events
    var galleryElements = document.querySelectorAll( gallerySelector );

    for(var i = 0, l = galleryElements.length; i < l; i++) {
        galleryElements[i].setAttribute('data-pswp-uid', i+1);
        galleryElements[i].onclick = onThumbnailsClick;
    }

    // Parse URL and open gallery if it contains #&pid=3&gid=1
    var hashData = photoswipeParseHash();
    if(hashData.pid && hashData.gid) {
        openPhotoSwipe( hashData.pid ,  galleryElements[ hashData.gid - 1 ], true, true );
    }
};

// execute above function
initPhotoSwipeFromDOM('.my-gallery');
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-100027039-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>
